DROP TABLE LOGS;
DROP TABLE EVENT_PLAYER;
DROP TABLE BOARDGAME_EVENT;
DROP TABLE BOARDGAMES;
DROP TABLE EVENTS;
DROP TABLE PLAYERS;
DROP SEQUENCE SEQ_LOGS;
DROP SEQUENCE SEQ_EVENT_PLAYER;
DROP SEQUENCE SEQ_BOARDGAME_EVENT;
DROP SEQUENCE SEQ_BOARDGAMES;
DROP SEQUENCE SEQ_EVENTS;
DROP SEQUENCE SEQ_PLAYERS;

CREATE TABLE PLAYERS(
	ID NUMBER PRIMARY KEY,
	FIRSTNAME VARCHAR(50),
	LASTNAME VARCHAR(50)
);

CREATE SEQUENCE SEQ_PLAYERS START WITH 1 INCREMENT BY 1 NOCYCLE;

CREATE OR REPLACE TRIGGER TRIG_PLAYERS
BEFORE INSERT ON PLAYERS
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
	WHEN (NEW.ID IS NULL)
BEGIN
   SELECT SEQ_PLAYERS.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/

CREATE TABLE EVENTS(
	ID NUMBER PRIMARY KEY,
	NAME VARCHAR(50),
	DESCRIPTION VARCHAR(256),
	DATESTART DATE DEFAULT (sysdate)
);

CREATE SEQUENCE SEQ_EVENTS START WITH 1 INCREMENT BY 1 NOCYCLE;

CREATE OR REPLACE TRIGGER TRIG_EVENTS
BEFORE INSERT ON EVENTS
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
	WHEN (NEW.ID IS NULL)
BEGIN
   SELECT SEQ_EVENTS.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/

CREATE TABLE BOARDGAMES(
	ID NUMBER PRIMARY KEY,
	NAME VARCHAR(50),
	MINIMUM_PLAYER_NUMBER NUMBER(2),
	MAXIMUM_PLAYER_NUMBER NUMBER(2),
	MINIMUM_AGE NUMBER(2),
	AVERAGE_GAME_TIME NUMBER(3)
);

CREATE SEQUENCE SEQ_BOARDGAMES START WITH 1 INCREMENT BY 1 NOCYCLE;

CREATE OR REPLACE TRIGGER TRIG_BOARDGAMES
BEFORE INSERT ON BOARDGAMES
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
	WHEN (NEW.ID IS NULL)
BEGIN
   SELECT SEQ_BOARDGAMES.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/

CREATE TABLE BOARDGAME_EVENT(
	ID NUMBER PRIMARY KEY,
	BOARDGAME_ID NUMBER CONSTRAINT FK_BOARDGAME_EVENT_BOARDGAME_ID REFERENCES BOARDGAMES(ID),
	EVENT_ID NUMBER CONSTRAINT FK_BOARDGAME_EVENT_EVENT_ID REFERENCES EVENTS(ID)
);

CREATE SEQUENCE SEQ_BOARDGAME_EVENT START WITH 1 INCREMENT BY 1 NOCYCLE;

CREATE OR REPLACE TRIGGER TRIG_BOARDGAME_EVENT
BEFORE INSERT ON BOARDGAME_EVENT
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
	WHEN (NEW.ID IS NULL)
BEGIN
   SELECT SEQ_BOARDGAME_EVENT.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/

CREATE TABLE EVENT_PLAYER(
	ID NUMBER PRIMARY KEY,
	PLAYER_ID NUMBER CONSTRAINT FK_EVENT_PLAYER_PLAYER_ID REFERENCES PLAYERS(ID),
	EVENT_ID NUMBER CONSTRAINT FK_EVENT_PLAYER_EVENT_ID REFERENCES EVENTS(ID)
);

CREATE SEQUENCE SEQ_EVENT_PLAYER START WITH 1 INCREMENT BY 1 NOCYCLE;

CREATE OR REPLACE TRIGGER TRIG_EVENT_PLAYER
BEFORE INSERT ON EVENT_PLAYER
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
	WHEN (NEW.ID IS NULL)
BEGIN
   SELECT SEQ_EVENT_PLAYER.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/

CREATE TABLE LOGS(	
	ID NUMBER PRIMARY KEY, 
	ACTION VARCHAR2(30) NOT NULL ENABLE, 
	COMMAND VARCHAR2(2000) DEFAULT NULL
);

CREATE SEQUENCE SEQ_LOGS START WITH 1 INCREMENT BY 1 NOCYCLE;

CREATE OR REPLACE TRIGGER TRIG_LOGS
BEFORE INSERT ON LOGS
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
	WHEN (NEW.ID IS NULL)
BEGIN
   SELECT SEQ_LOGS.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/

/* INDEXES */
CREATE INDEX IDX_BOARDGAMES_AVERAGE_GAME_TIME ON BOARDGAMES(AVERAGE_GAME_TIME);
CREATE INDEX IDX_BOARDGAMES_MINIMUM_AGE ON BOARDGAMES(MINIMUM_AGE);
CREATE INDEX IDX_PLAYERS_LASTNAME ON PLAYERS(LASTNAME);
CREATE INDEX IDX_EVENTS_DATESTART ON EVENTS(DATESTART);
  
/* VIEWS */
CREATE VIEW V_UPCOMING_EVENTS AS 
  SELECT UPCOMING_EVENTS.*, BOARDGAMES.NAME, BOARDGAMES.MINIMUM_PLAYER_NUMBER, BOARDGAMES.MAXIMUM_PLAYER_NUMBER, BOARDGAMES.MINIMUM_AGE, BOARDGAMES.AVERAGE_GAME_TIME
  FROM (SELECT ID, NAME, DESCRIPTION, DATESTART FROM EVENTS WHERE DATESTART >= to_char(SYSDATE, 'MM-DD-YYYY')) UPCOMING_EVENTS 
  INNER JOIN BOARDGAME_EVENT ON BOARDGAME_EVENT.EVENT_ID = UPCOMING_EVENTS.ID
  INNER JOIN BOARDGAMES ON BOARDGAME_EVENT.BOARDGAME_ID = BOARDGAMES.ID;

/* INSERT PLAYERS */
INSERT INTO PLAYERS (FIRSTNAME, LASTNAME) VALUES ('Michael', 'Durham');
INSERT INTO PLAYERS (FIRSTNAME, LASTNAME) VALUES ('Coleen', 'Billy');
INSERT INTO PLAYERS (FIRSTNAME, LASTNAME) VALUES ('Jeff', 'Tawnie');
INSERT INTO PLAYERS (FIRSTNAME, LASTNAME) VALUES ('Britannia', 'Makenna');
INSERT INTO PLAYERS (FIRSTNAME, LASTNAME) VALUES ('Sandra', 'Fournier');
INSERT INTO PLAYERS (FIRSTNAME, LASTNAME) VALUES ('Bryan', 'Robinson');
INSERT INTO PLAYERS (FIRSTNAME, LASTNAME) VALUES ('Katie', 'Kemp');
INSERT INTO PLAYERS (FIRSTNAME, LASTNAME) VALUES ('Nathan', 'Dillon');

/* INSERT BOARDGAMES */
INSERT INTO BOARDGAMES (NAME, DESCRIPTION, DATESTART) VALUES ('Cosmic Encounter', 'Build a galactic empire... In the depths of space, the alien races of the Cosmos vie with each other for control of the universe.', '01-DEC-14');
INSERT INTO BOARDGAMES (NAME, DESCRIPTION, DATESTART) VALUES ('Heroscape Master Set: Rise of the Valkyrie', 'This Fantasy Battle Board Game comes with dozens of painted plastic miniatures, each representing a warrior from a different era, and hex-based hard plastic terrain pieces which can be put together in many different ways.', '11-MAY-15');
INSERT INTO BOARDGAMES (NAME, DESCRIPTION, DATESTART) VALUES ('Descent: Journeys in the Dark ', 'Descent: Journeys in the Dark (Second Edition) is a board game in which one player takes on the role of the treacherous overlord, and up to four other players take on the roles of courageous heroes.', '07-JUN-15');
INSERT INTO BOARDGAMES (NAME, DESCRIPTION, DATESTART) VALUES ('Mage Wars', 'Mage Wars pits powerful Mages against each other in deadly arena combat. Each Mage uses his own fully-customizable book of spells to achieve total victory over his opponent.', '22-JUL-15');
INSERT INTO BOARDGAMES (NAME, DESCRIPTION, DATESTART) VALUES ('Summoner Wars', 'Summoner Wars is a fast-playing, action-packed 2-4 player card game. Players take on the role of Summoners: powerful beings who harness the power of mysterious Summoning Stones to lead their race to conquest on the war-torn planet of Itharia.', '13-AUG-15');
INSERT INTO BOARDGAMES (NAME, DESCRIPTION, DATESTART) VALUES ('Duel of Ages II', 'Duel of Ages II is a time-scramble board game played between two opposing sides each having 1 to 4 players, with uneven size allowable.', '13-JAN-15');
INSERT INTO BOARDGAMES (NAME, DESCRIPTION, DATESTART) VALUES ('Caverna: The Cave Farmers', 'Following along the same lines as its predecessor (Agricola), Caverna: The Cave Farmers is a worker-placement game at heart, with a focus on farming. In the game, you are the bearded leader of a small dwarf family that lives in a little cave in the mountains.', '27-FEB-15');
INSERT INTO BOARDGAMES (NAME, DESCRIPTION, DATESTART) VALUES ('Le Havre', 'In Le Havre, a player’s turn consists of two parts: First, distribute newly supplied goods onto the offer spaces; then take an action. As an action, players may choose either to take all goods of one type from an offer space or to use one of the available buildings.', '23-JUN-15');

/* INSERT EVENTS */

COMMIT;